---
- name: F5 BIGip Device Facts
  hosts: bigip
  gather_facts: False
  
  # vars:
  #   cancelprecheck: false #F5 precheck 
  #   provider:

  #     password: "{{ ansible_ssh_pass }}"
  #     server: "{{ ansible_host }}"
  #     user: "{{ ansible_user }}"
  #     validate_certs: False
  vars_prompt:

    - name: username
      prompt: What is your username?
      private: false

    - name: password
      prompt: What is your password?
      private: true

  tasks:
    - name: Collect BIG-IP information
      bigip_device_info:
        gather_subset:
          - interfaces
          - ltm-pools
        provider:
          server: 10.14.255.233
          user: "{{ username }}"
          password: "{{ password }}"
          validate_certs: false
      delegate_to: localhost
      register: interface_output
    
    - name: print registered output
      ansible.builtin.debug:
       var: interface_output